# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Docker - Build and Push

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4

    - name: BUILD and PUSH the Docker image
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_LOGIN_NAME }}
        password: ${{ secrets.REGISTRY_LOGIN_PASSWORD }}
      
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/footyapp:latest
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/footyapp:latest
