# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Scheduler - Stop

# run at 1am each day!
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

jobs:
  connect-and-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the Azure CLI to show the current resource group
      - name: Azure CLI script - show FootRG
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group show --name FootRG

      
      # - name: Azure container app env - delete
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az containerapp env delete \
      #       -g my-container-apps \
      #       -n my-container-apps \
      #       --no-wait true --yes

      - name: Azure container app stop
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp job stop -g my-container-apps -n my-container-apps --yes

