# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Scehduler - Start


# run at 1am each day!
on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Create annotation
      run: echo "Starting the run"
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the Azure CLI to show the current account logged in
      # az containerapp list
      - name: Azure CLI script - show FootRG
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group show --name FootRG

      - name: Azure container app - Up
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp create -n my-container-app \
            -g FootRG \
            --image seanrreg.azurecr.io/footyapp:latest \
            --environment footyappenv \
            --cpu 0.5 --memory 1.0Gi \
            --min-replicas 4 --max-replicas 8


        # az containerapp up \
        # --name my-container-app \
        # --resource-group FootRG \
        # --location northeurope \
        # --environment 'my-container-apps' \
        # --image mcr.microsoft.com/k8se/quickstart:latest \
        # --target-port 80 \
        # --ingress external \
        # --query properties.configuration.ingress.fqdn



