# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Scehduler - Start


# run at 1am each day!
on:
  schedule:
    - cron: 0 10 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Create annotation
      run: echo "Starting the run"


