# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Schedule - Stop - Scale Up


# run at 1am each day!
on:
  schedule:
    - cron: 0 10 * * *
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Create annotation
      run: echo "Starting the run"
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the Azure CLI to show the current account logged in
      - name: Azure CLI script - show FootRG
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group show --name FootRG

      - name: Azure container app scale up
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp update -n my-container-app -g FootRG \
            --cpu 1.0 --memory 2.0Gi \
            --min-replicas 1 --max-replicas 3

      ##### Test flow for creating or updating an existing container app
      # - name: Azure Create or Update Container App
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az containerapp up \
      #       --name my-container-app \
      #       --resource-group FootRG \
      #       --location northeurope \
      #       --environment 'my-container-apps' \
      #       --image seanrreg.azurecr.io/footyapp:latest \
      #       --registry-password ${{ secrets.REGISTRY_LOGIN_PASSWORD }} \
      #       --registry-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
      #       --registry-username ${{ secrets.REGISTRY_LOGIN_NAME }} \
      #       --target-port 8080 \
      #       --ingress external \
      #       --query properties.configuration.ingress.fqdn
