# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Scheduler - Stop - Scale Down

# run at 1am each day!
on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

jobs:
  connect-and-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the Azure CLI to show the current resource group
      - name: Azure CLI script - show FootRG
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az group show --name FootRG

      - name: Azure container app scale down
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az containerapp update -n my-container-app -g FootRG \
            --cpu 0.25 --memory 0.5Gi \
            --min-replicas 0 --max-replicas 2